/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zaRnnBOBgYx
 */
import { Button } from "@/components/ui/button"

type NoDataProps = {
  onRefreshData?: () => void
}

export function NoData({ onRefreshData }: NoDataProps) {

  const reloadData = () => {
    onRefreshData?.()
  }

  return (
    <div className="flex flex-col items-center justify-center space-y-4 p-4">
      <div className="text-xl font-bold">暫無資料</div>
      {/* <img
        alt="Placeholder"
        className="w-48 h-48 object-cover rounded-md"
        height="200"
        src="/placeholder.svg"
        style={{
          aspectRatio: "200/200",
          objectFit: "cover",
        }}
        width="200"
      /> */}
      <p className="text-gray-500">資料將會在此顯示</p>
      {onRefreshData && <Button size="lg" variant="link" onClick={reloadData}>
        重新仔入
      </Button>}
    </div>
  )
}
